name: Deploy on hml
# Trigger apenas quando um PR para a branch hml for fechado
on:
  pull_request:
    types: [closed]
    branches:
      - hml
    paths:
      - 'force-app/**'
      - 'manifest/**'

jobs:
  merge_job:
    # Executa apenas se o PR foi mesclado
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl jq
          npm install @salesforce/cli --global
      
      - name: Autenticar no Salesforce
        run: echo ${{ secrets.AUTH_URL_HML }} > sfdx-auth-url.txt
      
      - name: Conectar ao Salesforce
        run: sf org login sfdx-url -f sfdx-auth-url.txt --alias hml
      
      - name: Executar Deploy (Dry Run)
        run: sf project deploy start --dry-run --test-level NoTestRun -x manifest/package.xml

  close_job:
    # Executa apenas se o PR foi fechado sem merge
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} foi fechada sem realizar o merge
